work with newest sqlite jdbc driver and runs faster
tuanna-hsp/stardict-to-sqlite pull request #2
Opened 2016-11-26 13:43 UTC by tsingakbar

[https://bitbucket.org/xerial/sqlite-jdbc/downloads](sqlite jdbc 3.15.1)

2016-11-27 14:30 UTC, tuanna-hsp requested changes

2016-11-27 14:30 UTC, tuanna-hsp commented on src/db/SQLiteHelper.java
> +            connection = DriverManager.getConnection("jdbc:sqlite:"+databaseName+".db");
Omit database name when creating connection will make the `SQLite JDBC` to store the new database in RAM, which allows very fast operations (after that we rewrite the content to disk in `writeDatabaseToDisk()`). 
So I dont think adding a database name here is a good choice.

2016-11-28 12:45 UTC, tsingakbar commented on src/db/SQLiteHelper.java
> +            connection = DriverManager.getConnection("jdbc:sqlite:"+databaseName+".db");
oh...I see.
I was converting one dictionary with your program, but the insert operation just endlessly blocked at the 3rd word.
I thought possibly it is your code won't work with my downloaded version of jdbc driver, so I followed jdbc driver's instruction to modify your code, but only to discovered that it your escape sql string don't work quite well.
In my opinion, memory table write then flush to disk is a better idea than my batch insert statment version. But other modifications such as preparedstatement should be adopted.
If we can shake on this, I will remove my batch insert statement code when I'm free.

2016-11-29 01:53 UTC, tuanna-hsp commented
Ok, that was the only problem. Others were good. Thank for contributing :)

2016/11/28 午後7:45 "Yu Qing" <notifications@github.com>:

> *@tsingakbar* commented on this pull request.
> ------------------------------
>
> In src/db/SQLiteHelper.java
> <https://github.com/tuanna-hsp/stardict-to-sqlite/pull/2>:
>
> > @@ -41,7 +44,7 @@ public SQLiteHelper() {
>      public void createDatabase(String databaseName) {
>          this.databaseName = databaseName;
>          try {
> -            connection = DriverManager.getConnection("jdbc:sqlite:");
> +            connection = DriverManager.getConnection("jdbc:sqlite:"+databaseName+".db");
>
> oh...I see.
> I was converting one dictionary with your program, but the insert
> operation just endlessly blocked at the 3rd word.
> I thought possibly it is your code won't work with my downloaded version
> of jdbc driver, so I followed jdbc driver's instruction to modify your
> code, but only to discovered that it your escape sql string don't work
> quite well.
> In my opinion, memory table write then flush to disk is a better idea than
> my batch insert statment version. But other modifications such as
> preparedstatement should be adopted.
> If we can shake on this, I will remove my batch insert statement code when
> I'm free.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tuanna-hsp/stardict-to-sqlite/pull/2>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/ANe2a-KMQFUWqrBPawcSspn14YZBmnSKks5rCszagaJpZM4K85cE>
> .
>

2016-11-30 14:09 UTC, tsingakbar commented
hey, I revised my code.
Also changed the synonym table codes to use prepared-statement, but I don't have a dictionary with synonym data, so pls help to verify it works for synonym data.

2016-11-30 14:38 UTC, tuanna-hsp commented
Thank you for your work, i will make a review later when i have time

2016/11/30 午後9:09 "Yu Qing" <notifications@github.com>:

> hey, I revised my code.
> Also changed the synonym table codes to use prepared-statement, but I
> don't have a dictionary with synonym data, so pls help to verify it works
> for synonym data.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tuanna-hsp/stardict-to-sqlite/pull/2#issuecomment-263882129>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ANe2a4RM2mzpD2Y3-aY96LQ4IWoSDhbsks5rDYO1gaJpZM4K85cE>
> .
>

2016-12-02 07:14 UTC, merged